export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SECCESS: 'LOGIN_SECCESS',
    LOGOUT: "LOGOUT",
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_FAIL: "REGISTER_FAIL",
    REGISTER_SECCESS: "REGISTER_SECCESS",
    REGISTER_REQUEST_DONE: "REGISTER_REQUEST_DONE",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE",
    LOGOUT_REQUEST:"LOGOUT_REQUEST"
}

export const categoryConstant = {
    GET_ALL_CATEGORIES_REQUEST:"GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS:"GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAIL:"GET_ALL_CATEGORIES_FAIL",
    ADD_NEW_CATEGORY_REQUEST:"ADD_ALL_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_ALL_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAIl:"ADD_NEW_CATEGORY_FAIl"
}

export const productConstant = {
    GET_PRODUCTS_BY_SLUG:"GET_PRODUCTS_BY_SLUG",
    GET_PRODUCT_PAGE_REQUEST:'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS:'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FALIUER:'GET_PRODUCT_PAGE_FALIUER',
    GET_PRODUCT_DETAILS_BY_ID_REQUEST:'GET_PRODUCT_DETAILS_BY_ID_REQUEST',
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS:'GET_PRODUCT_DETAILS_BY_ID_SUCCESS',
    GET_PRODUCT_DETAILS_BY_ID_FAILEUR:'GET_PRODUCT_DETAILS_BY_ID_FAILEUR'

}

export const cartConstant = {
    ADD_TO_CART:'ADD_TO_CART',
    ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
    ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
    ADD_TO_CART_FALIUR:'ADD_TO_CART_FALIUR',
    RESET_CART:"RESET_CART"
}

// export 