
export const categoryConstant = {
    GET_ALL_CATEGORIES_REQUEST:"GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS:"GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAIL:"GET_ALL_CATEGORIES_FAIL",
    ADD_NEW_CATEGORY_REQUEST:"ADD_ALL_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_ALL_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAIl:"ADD_NEW_CATEGORY_FAIl"
}

export const productConstant = {
    GET_PRODUCTS_BY_SLUG:"GET_PRODUCTS_BY_SLUG"
}

// export 