export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SECCESS: 'LOGIN_SECCESS',
    LOGOUT: "LOGOUT",
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_FAIL: "REGISTER_FAIL",
    REGISTER_SECCESS: "REGISTER_SECCESS",
    REGISTER_REQUEST_DONE: "REGISTER_REQUEST_DONE",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE:"LOGOUT_FAILURE",
    LOGOUT_REQUEST:"LOGOUT_REQUEST"
}

export const categoryConstant = {
    GET_ALL_CATEGORIES_REQUEST:"GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS:"GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAIL:"GET_ALL_CATEGORIES_FAIL",
    ADD_NEW_CATEGORY_REQUEST:"ADD_ALL_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS:"ADD_ALL_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAIl:"ADD_NEW_CATEGORY_FAIl",
    UPDATE_CATEGORIES_REQUEST:"UPDATE_CATEGORIES_REQUEST",
    UPDATE_CATEGORIES_SUCCESS:"UPDATE_CATEGORIES_SUCCESS",
    UPDATE_CATEGORIES_FALIUR:"UPDATE_CATEGORIES_FALIUR",
    DELETE_CATEGORIES_REQUEST:"DELETE_CATEGORIES_REQUEST",
    DELETE_CATEGORIES_SUCCESS:"DELETE_CATEGORIES_SUCCESS",
    DELETE_CATEGORIES_FAILUER:"DELETE_CATEGORIES_FAILUER",
    
}

export const ProductConnstant = {
    ADD_NEW_PRODUCT_REQUEST:"ADD_NEW_PRODUCT_REQUEST",
    ADD_NEW_PRODUCT_SUCCESS:"ADD_NEW_PRODUCT_SUCCESS",
    ADD_NEW_PRODUCT_FAIl:"ADD_NEW_PRODUCT_FAIl",
    GET_ALL_PRODUCTs_REQUEST:"GET_ALL_PRODUCTs_REQUEST",
    GET_ALL_PRODUCTs_SUCCESS:"GET_ALL_PRODUCTs_SUCCESS",
    GET_ALL_PRODUCTs_FAIl:"GET_ALL_PRODUCTs_FAIl",
    
}

export const initilData = {
    GET_ALL_INITIAL_DATA_REQUEST : 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS : 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILIUR : 'GET_ALL_INITIAL_DATA_FAILIUR'   
}


export const createPageCOnstant = {
    CREATE_PAGE_REQUEST:'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS:'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FALIUER:'CREATE_PAGE_FALIUER'   
}